import { Injectable } from '@angular/core';
import { MathTerm } from '../model/math-term.model';

@Injectable({
  providedIn: 'root',
})
export class MathTermService {
  mathTermList: MathTerm[] = [
    {
      id: 0,
      name: 'Açınım',
      description: 'Geometrik cisimlerin yüzeyinin düzlemsel olarak açılması.',
      type: '5.Sınıf',
      photo: '/assets/alan.png',
      availableUnits: 4,
      wifi: true,
      laundry: true,
    },
    {
      id: 1,
      name: 'Alan',
      description: 'Sınırlı bir bölge yüzeyinin büyüklüğüdür',
      type: '5.Sınıf',
      photo: '/assets/acinim.png',
      availableUnits: 0,
      wifi: false,
      laundry: true,
    },
    {
      id: 2,
      name: 'Aritmetik Ortalama',
      description:
        'Bir diziyi oluşturan sayısal değerler toplamının o dizide yer alan değerler sayısına bölünmesiyle elde edilen sonuç',
      type: '5.Sınıf',
      photo: '/assets/aritmetik_ortalama.png',
      availableUnits: 1,
      wifi: false,
      laundry: false,
    },
    {
      id: 3,
      name: 'Atatürk ve matematik',
      description:
        'Atatürk, 1936 ile 1937 yıllarında “Geometri” isimli bir kitap yazmış ve yazdıklarının bir kısmını okullarda ders olarak anlatmıştır. Bugün kullandığımız pek çok matematik teriminin Türkçe karşılığını bulmuştur. Ayrıca ölçüler konusunda uluslararası standartlar getirmiştir',
      type: '5.Sınıf',
      photo: '/assets/ataturk_geometri.jpg',
      availableUnits: 1,
      wifi: true,
      laundry: false,
    },
    {
      id: 4,
      name: 'Boyut',
      description:
        'Doğruların, yüzeylerin veya cisimlerin ölçülmesinde ele alınan üç doğrultudan –“uzunluk”, “genişlik” ve “derinlik”– her biri.(Nesnelerin cinsi, yeri ve duruşlarına göre bazı hâllerde “uzunluk”, “en”, “yükseklik” , bazı durumlarda her birinin yerine sırasıyla “boy”, “çap”, veya “kalınlık” ifadeleri kullanılır.)',
      type: '5.Sınıf',
      photo: '/assets/boyut.jpeg',
      availableUnits: 1,
      wifi: true,
      laundry: false,
    },
    {
      id: 5,
      name: 'Çember',
      description:
        'Düzlemde sabit bir noktadan eşit uzaklıkta bulunan noktaların oluşturduğu kapalı eğri. (Dikkat! Çember ile daire farklı geometrik ifadelerdir. Daire, bir çemberle bu çemberin sınırladığı düzlemsel bölgedir.)',
      type: '5.Sınıf',
      photo: '/assets/cember.png',
      availableUnits: 2,
      wifi: true,
      laundry: true,
    },
    {
      id: 6,
      name: 'Çizgi Grafiği',
      description:
        'Anket, istatistik gibi araştırma sonuçlarını gösteren ve tüm verilerin bir çizgi üzerinde kesiştiği grafik türü. (Her olay çizgi grafiğine uygun değildir.)',
      type: '5.Sınıf',
      photo: '/assets/cizgi_grafigi.png',
      availableUnits: 5,
      wifi: true,
      laundry: true,
    },
    {
      id: 7,
      name: 'Çokgen',
      description:
        'Düzlemde üç ya da daha fazla doğru parçasının oluşturduğu kapalı şekil',
      type: '5.Sınıf',
      photo: '/assets/cokgen.png',
      availableUnits: 2,
      wifi: true,
      laundry: true,
    },
    {
      id: 8,
      name: 'Daire',
      description:
        'Bir çemberle bu çemberin sınırladığı düzlemsel bölgedir. (Dikkat! Çember ile daire farklı geometrik ifadelerdir. Çember, düzlemde sabit bir noktadan eşit uzaklıkta bulunan noktaların oluşturduğu kapalı eğridir',
      type: '5.Sınıf',
      photo: '/assets/daire.png',
      availableUnits: 10,
      wifi: false,
      laundry: false,
    },
    {
      id: 9,
      name: 'Denk Kesir',
      description: 'Bir bütünde aynı oranı gösteren kesir.',
      type: '5.Sınıf',
      photo: '/assets/denk_kesir.png',
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
    {
      id: 10,
      name: 'Dikdörtgen',
      description: 'Bütün açıları dik olan dörtgen.',
      type: '5.Sınıf',
      photo: '/assets/dikdortgen.png',
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
    {
      id: 11,
      name: 'Dikdörtgen Piramit:',
      description:
        'Tepeleri ortak bir noktada birleşen, tabanları da bir dikdörtgenin birer kenarı olan üçgenlerden oluşmuş geometrik cisim.',
      type: '5.Sınıf',
      photo: '/assets/dikdortgen_piramit.png',
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
    {
      id: 12,
      name: 'Dikdörtgenler Prizması:',
      description:
        'Tabanları ve karşılıklı yan yüzleri birbirine paralel dikdörtgensel bölge olan geometrik cisim.',
      type: '5.Sınıf',
      photo: '/assets/dikdortgenler_prizmasi.png',
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
    {
      id: 13,
      name: 'Doğal Sayı',
      description:
        '0, 1, 2, 3, ... olarak sonsuza kadar giden sayılardan her biri.',
      type: '5.Sınıf',
      photo: '/assets/dogal_sayi.png',
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
    {
      id: 14,
      name: 'Düzgün Çokgen',
      description:
        'Tüm kenarlarının uzunlukları ve iç açılarının ölçüleri eşit olan çokgen.(Sadece açılarının ölçüleri ya da sadece kenarlarının uzunlukları eşit olan çokgenler düzgün çokgen değildir. Örneğin dikdörtgenin tüm iç açıları eşit ama düzgün değildir. Yine eşkenar dörtgenin tüm kenarları eşittir ama düzgün çokgen değildir.)',
      type: '5.Sınıf',
      photo: '/assets/duzgun_cokgen.png',
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
    {
      id: 15,
      name: 'Düzlem',
      description: 'Uzunluğu ve genişliği olan iki boyutlu nesne.',
      type: '5.Sınıf',
      photo: '/assets/duzlem.png',
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
    {
      id: 16,
      name: 'Eş Küpler:',
      description: 'Her yönden birbirinin eşi olan küpler.',
      type: '5.Sınıf',
      photo: '/assets/es_kupler.png',
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
    {
      id: 17,
      name: 'Eşkenar Dörtgen:',
      description:
        'Bütün kenar uzunlukları ve karşılıklı açıları birbirine eşit olan dörtgen. (Kare de bir çeşit eşkenar dörtgendir.)',
      type: '5.Sınıf',
      photo: '/assets/eskenar_dortgen.png',
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
    {
      id: 18,
      name: 'Hacim',
      description: 'Bir cismin uzayda doldurduğu boşluk.',
      type: '5.Sınıf',
      photo: '/assets/hacim.png',
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
    {
      id: 19,
      name: 'Kare:',
      description:
        'Bütün açıları dik ve bütün kenarları birbirine eşit olan düzgün dörtgen',
      type: '5.Sınıf',
      photo: '/assets/kare.png',
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
    {
      id: 20,
      name: 'Kare Piramit:',
      description:
        'Tepeleri ortak bir noktada birleşen, tabanları da bir karenin birer kenarı olan üçgenlerden oluşmuş geometrik cisim.',
      type: '5.Sınıf',
      photo: '/assets/kare_piramit.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 21,
      name: 'kare prizma',
      description:
        'Tabanları birbirine paralel karesel bölge ve karşılıklı yan yüzleri birbirine paralel dikdörtgensel bölge olan geometrik cisim.',
      type: '5.Sınıf',
      photo: '/assets/kare_prizma.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 22,
      name: 'kesirleri birbirine çevirme:',
      description: 'Bileşik kesri tam sayılı kesre, tam sayılı kesri bileşik kesre dönüştürmek.',
      type: '5.Sınıf',
      photo: '/assets/kesirleri_birbirine_cevirme.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 23,
      name: 'kesirleri karşılaştırma',
      description: 'Kesirlerin belirttikleri büyüklükleri inceleyerek birbirine göre büyük, küçük ya da eşit olduklarını belirtmek.',
      type: '5.Sınıf',
      photo: '/assets/kesirleri_karsilastirma.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 24,
      name: 'kesirleri sıralama',
      description: 'Kesirleri belirttikleri büyüklüklere göre büyükten küçüğe ya da küçükten büyüğe doğru sıralamak.',
      type: '5.Sınıf',
      photo: '/assets/kesirleri_siralama.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 25,
      name: 'kesirlerle çarpma işlemi:',
      description: 'Bir kesrin diğer bir kesir kadarını belirleme.',
      type: '5.Sınıf',
      photo: '/assets/kesirlerle_carpma_islemi.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 26,
      name: 'kesirlerle çıkarma işlemi',
      description:
        'Kesirleri veya kesirlerin belirttiği nicelikleri birbirinden eksiltip farkı bulma işlemi.',
      type: '5.Sınıf',
      photo: '/assets/kesirlerle_cikarma_islemi.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 27,
      name: 'kesirlerle toplama işlemi:',
      description:
        'Kesirleri veya kesirlerin belirttiği nicelikleri birbirine ekleyip toplamını bulma işlemi.',
      type: '5.Sınıf',
      photo: '/assets/kesirlerle_toplama_islemi.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 28,
      name: 'kesri verilen bütünü bulma:',
      description:
        'Bir basit kesir kadarı verilen çokluğun tamamını belirlemek.',
      type: '5.Sınıf',
      photo: '/assets/kesri_verilen_butunu_bulma.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 29,
      name: 'kısa yoldan bölme işlemi',
      description:
        'Son üç basamağı sıfır olan en çok yedi basamaklı doğal sayıları 10’un, 100’ün ve 1000’in en çok dokuz katı olan doğal sayılara kısa yoldan bölme işlemi.',
      type: '5.Sınıf',
      photo: '/assets/kisa_yoldan_bolme_islemi.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 30,
      name: 'kısa yoldan çarpma işlemi:',
      description:
        'En çok dört basamaklı doğal sayılarla 10’un, 100’ün ve 1000’in en çok dokuz katı olan doğal sayıları kısa yoldan çarpma işlemi.',
      type: '5.Sınıf',
      photo: '/assets/kisa_yoldan_carpma_islemi.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 31,
      name: 'küp',
      description: 'Tüm yüzleri karesel bölge olan prizma.',
      type: '5.Sınıf',
      photo: '/assets/kup.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 32,
      name: 'olasılık',
      description:
        'Bir olayın olabilirlik derecesinin 0 ile 1 arasındaki bir oranla gösterilmiş biçimi',
      type: '5.Sınıf',
      photo: '/assets/olasilik.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 33,
      name: 'ondalık kesir:',
      description: 'Paydası 10, 100 veya 1000 olan kesir',
      type: '5.Sınıf',
      photo: '/assets/ondalik_kesir.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 34,
      name: 'ondalık kesir oluşturma',
      description:
        'Verilen rakamları bir kez kullanarak, virgül yardımıyla çeşitli ondalık kesirler elde etmek.',
      type: '5.Sınıf',
      photo: '/assets/ondalik_kesir_olusturma.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 35,
      name: 'ondalık kesirleri karşılaştırma:',
      description: 'Ondalık kesirleri basamaklarındaki sayı değerleri incelenerek küçükten büyüğe ya da büyükten küçüğe sırlamak.',
      type: '5.Sınıf',
      photo: '/assets/ondalik_kesirleri_karsilastirma.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 36,
      name: 'ondalık kesirlerle çıkarma işlemi:',
      description: 'Ondalık kesirlerin belirttiği nicelikleri birbirinden eksiltip farkını bulma işlemi.',
      type: '5.Sınıf',
      photo: '/assets/ondalik_kesirlerle_cikarma_islemi.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 37,
      name: 'ondalık kesirlerle toplama işlemi:',
      description: 'Ondalık kesirlerin belirttiği nicelikleri birbirine ekleyip toplamını bulma işlemi.',
      type: '5.Sınıf',
      photo: '/assets/ondalık_kesirlerle_toplama_islemi.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 38,
      name: 'oran',
      description:
        'İki nesne arasında büyüklük, nicelik, derece bakımından veya parça ile bütün arasında bulunan ilişki.',
      type: '5.Sınıf',
      photo: '/assets/oran.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 39,
      name: 'örüntü (sayı):',
      description:
        'Sayıların belirli bir kural çerçevesinde birbirini takip ederek gelmesi.',
      type: '5.Sınıf',
      photo: '/assets/oruntu.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 40,
      name: 'paralelkenar',
      description: 'Karşılıklı kenarları eşit ve paralel olan dörtgen.',
      type: '5.Sınıf',
      photo: '/assets/paralelkenar.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 41,
      name: 'pi:',
      description: 'Çemberin ya da dairenin çevre uzunluğunun çap uzunluğuna oranı. (π= 3,14159265… olarak devam eden bir sayıdır. Bu sınıf düzeyinde π kısaca 3,14 ya da 3 olarak kullanılacaktır.)',
      type: '5.Sınıf',
      photo: '/assets/pi.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 42,
      name: 'sıvıları ölçme:',
      description:
        'Sıvıların miktarını uygun araçlar ve yöntemler uygulayarak sayısal sonuçlarla belirlemek.',
      type: '5.Sınıf',
      photo: '/assets/sivilari_olcme.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 43,
      name: 'simetri:',
      description:
        'İki ya da daha çok nesne arasında konum, biçim ve belirli bir eksene göre ölçü uygunluğu.',
      type: '5.Sınıf',
      photo: '/assets/simetri.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 44,
      name: 'süsleme',
      description:
        'Verilen rakamları bir kez kullanarak, virgül yardımıyla çeşitli ondalık kesirler elde etmek.',
      type: '5.Sınıf',
      photo: '/assets/süsleme.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 45,
      name: 'şema',
      description:
        'Bazı verileri veya verilere dayalı ayrıntıları çizimle gösterme',
      type: '5.Sınıf',
      photo: '/assets/sema.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 46,
      name: 'tablo',
      description:
        'Birbiriyle olan ilgilerine göre düzenlenerek yazılmış verilerin hepsi:',
      type: '5.Sınıf',
      photo: '/assets/tablo.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 47,
      name: 'uzay',
      description: 'Nesnelerin içinde bulunduğu yer.',
      type: '5.Sınıf',
      photo: '/assets/uzay.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 48,
      name: 'uzunlukları ölçme',
      description:
        'Bir nesnenin bir ucundan öbür ucuna kadar olan uzaklığını ya da iki nokta arasındaki uzaklığı uygun araçlar ve yöntemler uygulayarak sayısal sonuçlarla belirlemek.',
      type: '5.Sınıf',
      photo: '/assets/uzunluklari_olcme.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 49,
      name: 'üçgen piramit:',
      description:
        'Tepeleri ortak bir noktada birleşen, tabanları da bir üçgenin birer kenarı olan üçgenlerden oluşmuş geometrik cisim.',
      type: '5.Sınıf',
      photo: '/assets/ucgen_piramit.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 50,
      name: 'üçgen prizma:',
      description:
        'Tabanları birbirine paralel üçgensel bölge ve yan yüzleri dikdörtgensel bölge olan geometrik cisim.',
      type: '5.Sınıf',
      photo: '/assets/ucgen_prizma.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 51,
      name: 'üçgenlerin sınıflandırılması:',
      description:
        'Üçgenlerin, açılarının dar, geniş ya da dik oluşuna ve kenarlarının çeşitkenar, ikizkenar ve eşkenar oluşuna göre sınıflandırılması.',
      type: '5.Sınıf',
      photo: '/assets/ucgenlerin_siniflandirilmasi.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 52,
      name: 'üslü gösterim:',
      description:
        'Bir doğal sayıyı , en fazla üç defa yan yana çarpma şeklinde yazarak kısa yoldan göstermek.',
      type: '5.Sınıf',
      photo: '/assets/uslu_gosterim.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 53,
      name: 'veri',
      description:
        'Ölçüm, sayım, deney, gözlem ya da araştırma yolu ile elde edilen sonuçlar.',
      type: '5.Sınıf',
      photo: '/assets/veri.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 54,
      name: 'yamuk:',
      description:
        'Karşılıklı kenar çiftlerinden en az biri paralel olan dörtgen',
      type: '5.Sınıf',
      photo: '/assets/yamuk.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 55,
      name: 'yuvarlama:',
      description:
        'Bir sayının çeşitli sebeplerle, birler, onlar ya da yüzler basamağındaki sayıların en yakın onluk, yüzlük ya da binliğe dönüştürülmesi.',
      type: '5.Sınıf',
      photo: '/assets/yuvarlama.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 56,
      name: 'yükseklik',
      description:
        'Nesnelerin tabanlarından tepelerine veya tepelerinden tabanlarına inilen dikmenin uzunluğu',
      type: '5.Sınıf',
      photo: '/assets/yukseklik.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 57,
      name: 'yüzde',
      description:
        'Bir bütünün 100 eş parçasından alınan miktarı gösteren ifade.',
      type: '5.Sınıf',
      photo: '/assets/yuzde',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 58,
      name: 'yüzdeleri karşılaştırma',
      description:
        'Bir bütünün 100 eş parçasından alınan miktarları gösteren ifadelerin karşılaştırılması.',
      type: '5.Sınıf',
      photo: '/assets/yuzdeleri_karsilastirma.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 59,
      name: 'yüzdeyi ondalık kesre çevirme:',
      description:
        'Bir bütünün 100 eş parçasından alınan miktarı gösteren ifadeyi ondalık kesir olarak yazma.',
      type: '5.Sınıf',
      photo: '/assets/yuzdeyi_ondalik_kesre_cevirme.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 60,
      name: 'zaman',
      description:
        'Bir işin, bir oluşun içinde geçtiği, geçeceği veya geçmekte olduğu süre.',
      type: '5.Sınıf',
      photo: '/assets/zaman.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 61,
      name: 'zihinden çarpma işlemi:',
      description:
        'En çok dört basamaklı doğal sayıları 10, 100 ve 1000 ile zihinden çarpma işlemi.',
      type: '5.Sınıf',
      photo: '/assets/zihinden_carpma_islemi.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 62,
      name: 'zihinden çıkarma işlemi:',
      description:
        'Dört basamaklı doğal sayılarla 10’un, 100’ün ve 1000’in en çok dokuz katı olan doğal sayıların çıkarma işlemi.',
      type: '5.Sınıf',
      photo: '/assets/zihinden_cikarma_islemi.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
    {
      id: 63,
      name: 'zihinden toplama işlemi',
      description:
        'Dört basamaklı doğal sayılarla 10’un, 100’ün ve 1000’in en çok dokuz katı olan doğal sayıların toplama işlemi.',
      type: '5.Sınıf',
      photo: '/assets/zihinden_toplama_islemi.png',
      availableUnits: 0,
      wifi: true,
      laundry: true,
    },
  ];

  constructor() {}

  getAllMathTerms(): MathTerm[] {
    return this.mathTermList;
  }

  getMathTermById(id: number): MathTerm | undefined {
    return this.mathTermList.find((mathTerm) => mathTerm.id === id);
  }

  submitApplication(firstName: string, lastName: string, email: string) {
    console.log(
      `Homes application recieved: firstName: ${firstName}, lastName: ${lastName}, email: ${email}.`
    );
  }
}
